<?php
namespace app\models;

use Yii;
use yii\base\Model;
use yii\db\Connection;
use yii\db\Query;

class Tecdoc extends Model
{
	// Brands section
	public static function getListSuppliers(){
		$data = Yii::$app->db->createCommand("SELECT * FROM SUPPLIERS ORDER BY SUP_ID DESC ")->queryAll();
		return $data;
	}
	public static function getListBrands(){
		$data = Yii::$app->db->createCommand("SELECT * FROM BRANDS ORDER BY BRA_BRAND ASC ")->queryAll();
		return $data;
	}
	static function getBrandsId($bra_id){
		$data = Yii::$app->db->createCommand("SELECT * FROM BRANDS WHERE BRA_ID = '$bra_id'")->queryOne();
		return $data;
	}
	// End Brands Section
	 
	public static function getListManufactured()
	{
		$data = Yii::$app->db->createCommand("SELECT MFA_ID, MFA_BRAND FROM MANUFACTURERS WHERE MFA_PC_MFC = '1' ORDER BY MFA_BRAND")->queryAll();
		return $data;
	}

	// Section Tecdoc Global
	public static function getManufacturedCar($id, $year)
	{
		$data = Yii::$app->db->createCommand("
			SELECT
			MOD_ID,
			mod_pc,
			MOD_CDS_ID,
			TEX_TEXT AS MOD_CDS_TEXT,
			MOD_PCON_START,
			MOD_PCON_END
			FROM MODELS
			INNER JOIN COUNTRY_DESIGNATIONS ON CDS_ID = MOD_CDS_ID
			INNER JOIN DES_TEXTS ON TEX_ID = CDS_TEX_ID
			WHERE
				MOD_MFA_ID = '$id' AND
				CDS_LNG_ID = '16' AND (MOD_PC = '1' AND MOD_CV = '0')
				AND (MOD_PCON_END >= '$year' OR MOD_PCON_END <=> NULL) AND MOD_PCON_START <= '$year'
			ORDER BY MOD_CDS_TEXT")->queryAll();
		return $data;
	}

	public static function getCarModel($carid)
	{
		$lng_id = '16';
		$data = Yii::$app->db->createCommand("
		SELECT
			TYP_ID,
			MFA_BRAND,
			DES_TEXTS7.TEX_TEXT AS MOD_CDS_TEXT,
			DES_TEXTS.TEX_TEXT AS TYP_CDS_TEXT,
			TYP_PCON_START,
			TYP_PCON_END,
			TYP_CCM,
			TYP_KW_FROM,
			TYP_KW_UPTO,
			TYP_HP_FROM,
			TYP_HP_UPTO,
			TYP_CYLINDERS,
			ENGINES.ENG_CODE,
			DES_TEXTS2.TEX_TEXT AS TYP_ENGINE_DES_TEXT,
			DES_TEXTS3.TEX_TEXT AS TYP_FUEL_DES_TEXT,
			IFNULL(DES_TEXTS4.TEX_TEXT, DES_TEXTS5.TEX_TEXT) AS TYP_BODY_DES_TEXT,
			DES_TEXTS6.TEX_TEXT AS TYP_AXLE_DES_TEXT,
			TYP_MAX_WEIGHT
			FROM TYPES
			INNER JOIN MODELS ON MOD_ID = TYP_MOD_ID
			INNER JOIN MANUFACTURERS ON MFA_ID = MOD_MFA_ID
			INNER JOIN COUNTRY_DESIGNATIONS AS COUNTRY_DESIGNATIONS2 ON COUNTRY_DESIGNATIONS2.CDS_ID = MOD_CDS_ID AND COUNTRY_DESIGNATIONS2.CDS_LNG_ID = '$lng_id'
			INNER JOIN DES_TEXTS AS DES_TEXTS7 ON DES_TEXTS7.TEX_ID = COUNTRY_DESIGNATIONS2.CDS_TEX_ID
			INNER JOIN COUNTRY_DESIGNATIONS ON COUNTRY_DESIGNATIONS.CDS_ID = TYP_CDS_ID AND COUNTRY_DESIGNATIONS.CDS_LNG_ID = '$lng_id'
			INNER JOIN DES_TEXTS ON DES_TEXTS.TEX_ID = COUNTRY_DESIGNATIONS.CDS_TEX_ID
			 LEFT JOIN DESIGNATIONS ON DESIGNATIONS.DES_ID = TYP_KV_ENGINE_DES_ID AND DESIGNATIONS.DES_LNG_ID = '$lng_id'
			 LEFT JOIN DES_TEXTS AS DES_TEXTS2 ON DES_TEXTS2.TEX_ID = DESIGNATIONS.DES_TEX_ID
			 LEFT JOIN DESIGNATIONS AS DESIGNATIONS2 ON DESIGNATIONS2.DES_ID = TYP_KV_FUEL_DES_ID AND DESIGNATIONS2.DES_LNG_ID = '$lng_id'
			 LEFT JOIN DES_TEXTS AS DES_TEXTS3 ON DES_TEXTS3.TEX_ID = DESIGNATIONS2.DES_TEX_ID
			 LEFT JOIN LINK_TYP_ENG ON LTE_TYP_ID = TYP_ID
			 LEFT JOIN ENGINES ON ENG_ID = LTE_ENG_ID
			 LEFT JOIN DESIGNATIONS AS DESIGNATIONS3 ON DESIGNATIONS3.DES_ID = TYP_KV_BODY_DES_ID AND DESIGNATIONS3.DES_LNG_ID = '$lng_id'
			 LEFT JOIN DES_TEXTS AS DES_TEXTS4 ON DES_TEXTS4.TEX_ID = DESIGNATIONS3.DES_TEX_ID
			 LEFT JOIN DESIGNATIONS AS DESIGNATIONS4 ON DESIGNATIONS4.DES_ID = TYP_KV_MODEL_DES_ID AND DESIGNATIONS4.DES_LNG_ID = '$lng_id'
			 LEFT JOIN DES_TEXTS AS DES_TEXTS5 ON DES_TEXTS5.TEX_ID = DESIGNATIONS4.DES_TEX_ID
			 LEFT JOIN DESIGNATIONS AS DESIGNATIONS5 ON DESIGNATIONS5.DES_ID = TYP_KV_AXLE_DES_ID AND DESIGNATIONS5.DES_LNG_ID = '$lng_id'
			 LEFT JOIN DES_TEXTS AS DES_TEXTS6 ON DES_TEXTS6.TEX_ID = DESIGNATIONS5.DES_TEX_ID
			WHERE
				TYP_MOD_ID = '$carid'
			ORDER BY
				MFA_BRAND,
				MOD_CDS_TEXT,
				TYP_CDS_TEXT,
				TYP_PCON_START,
				TYP_CCM
			LIMIT	100
		")->queryAll();
		return $data;
	}

	public static function getTree($typ_id, $str_id)
	{
		// $typ_id  = '3822';
		$lng_id = '16';
		//$str_id = '10001';
		$data = Yii::$app->db->createCommand("
		SELECT
			STR_ID,
			TEX_TEXT AS STR_DES_TEXT,
				IF(
					EXISTS(
						SELECT * FROM
	        	SEARCH_TREE AS SEARCH_TREE2
						WHERE
						SEARCH_TREE2.STR_ID_PARENT <=> SEARCH_TREE.STR_ID
						LIMIT 1
					), 1, 0) AS DESCENDANTS
				FROM
	       SEARCH_TREE
	INNER JOIN DESIGNATIONS ON DES_ID = STR_DES_ID
	INNER JOIN DES_TEXTS ON TEX_ID = DES_TEX_ID
WHERE
	STR_ID_PARENT <=> '$str_id' AND
	DES_LNG_ID = '$lng_id' AND
	EXISTS (
		SELECT
			*
		FROM
			           LINK_GA_STR
			INNER JOIN LINK_LA_TYP ON LAT_TYP_ID = '$typ_id' AND
			                          LAT_GA_ID = LGS_GA_ID
			INNER JOIN LINK_ART ON LA_ID = LAT_LA_ID
		WHERE
			LGS_STR_ID = STR_ID
		LIMIT
			1
	)
		")->queryAll();
		return $data;
	}

	public static function getTree2($typ_id, $str_id)
	{
		$lng_id = '16';
		$data = Yii::$app->db->createCommand("
		SELECT 	LA_ART_ID
		FROM LINK_GA_STR
		INNER JOIN LINK_LA_TYP ON LAT_TYP_ID = $typ_id AND
	                          LAT_GA_ID = LGS_GA_ID
		INNER JOIN LINK_ART ON LA_ID = LAT_LA_ID
		WHERE LGS_STR_ID <=> $str_id
		ORDER BY	LA_ART_ID 
		")->queryAll();
		return $data;
	}

	public static function articles($art_id)
	{
		$lng_id = '16';
		$data = Yii::$app->db->createCommand("
		SELECT
			ART_ARTICLE_NR,
			SUP_BRAND,
			DES_TEXTS.TEX_TEXT AS ART_COMPLETE_DES_TEXT,
			DES_TEXTS2.TEX_TEXT AS ART_DES_TEXT,
			DES_TEXTS3.TEX_TEXT AS ART_STATUS_TEXT
		FROM ARTICLES
		INNER JOIN DESIGNATIONS ON DESIGNATIONS.DES_ID = ART_COMPLETE_DES_ID
		AND DESIGNATIONS.DES_LNG_ID = $lng_id
		INNER JOIN DES_TEXTS ON DES_TEXTS.TEX_ID = DESIGNATIONS.DES_TEX_ID
	 	LEFT JOIN DESIGNATIONS AS DESIGNATIONS2 ON DESIGNATIONS2.DES_ID = ART_DES_ID
		AND DESIGNATIONS2.DES_LNG_ID = $lng_id
	 	LEFT JOIN DES_TEXTS AS DES_TEXTS2 ON DES_TEXTS2.TEX_ID = DESIGNATIONS2.DES_TEX_ID
		INNER JOIN SUPPLIERS ON SUP_ID = ART_SUP_ID
		INNER JOIN ART_COUNTRY_SPECIFICS ON ACS_ART_ID = ART_ID
		INNER JOIN DESIGNATIONS AS DESIGNATIONS3 ON DESIGNATIONS3.DES_ID = ACS_KV_STATUS_DES_ID
		AND DESIGNATIONS3.DES_LNG_ID = $lng_id
		INNER JOIN DES_TEXTS AS DES_TEXTS3 ON DES_TEXTS3.TEX_ID = DESIGNATIONS3.DES_TEX_ID
		WHERE ART_ID = $art_id")->queryOne();
		return $data;
	}

	public static function art_lookup($number)
	{
		$lng_id = '16';
		$data = Yii::$app->db->createCommand("
		SELECT DISTINCT
			IF (ART_LOOKUP.ARL_KIND IN (3, 4), BRANDS.BRA_BRAND, SUPPLIERS.SUP_BRAND) AS BRAND,
			ART_LOOKUP.ARL_SEARCH_NUMBER AS NUMBER,
			ART_LOOKUP.ARL_KIND,
			ART_LOOKUP.ARL_ART_ID,
			DES_TEXTS.TEX_TEXT AS ART_COMPLETE_DES_TEXT
		FROM ART_LOOKUP
	 	LEFT JOIN BRANDS ON BRANDS.BRA_ID = ART_LOOKUP.ARL_BRA_ID
		INNER JOIN ARTICLES ON ARTICLES.ART_ID = ART_LOOKUP.ARL_ART_ID
		INNER JOIN SUPPLIERS ON SUPPLIERS.SUP_ID = ARTICLES.ART_SUP_ID
		INNER JOIN DESIGNATIONS ON DESIGNATIONS.DES_ID = ARTICLES.ART_COMPLETE_DES_ID
		INNER JOIN DES_TEXTS ON DES_TEXTS.TEX_ID = DESIGNATIONS.DES_TEX_ID
		WHERE
			ART_LOOKUP.ARL_SEARCH_NUMBER = '$number' AND
			ART_LOOKUP.ARL_KIND IN (1, 2, 3, 4) AND
			DESIGNATIONS.DES_LNG_ID = '$lng_id'
		GROUP BY	BRAND,NUMBER;")->queryAll();
		return $data;
	}
}